# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mi lugar en la Red
email: khf1988@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my brand new personal site. You will find information about me, my interests
  what are my skills and much more
baseurl: "" # the subpath of your site, e.g. /blog
url: https://karlheitmann.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KarlHeitmann
tagline: Una p√°gina web donde coloco mi curriculum y algunas reflexiones personales. Viva el capitalismo.
# Build settings
markdown: kramdown
google_analytics: UA-159664384-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - sections/estudios.html
  - sections/artes.html
  - sections/reflexiones.html
  - sections/proyectos.html
  - sections/about.html
  # - blog.html

  # - about.md

urls:
    - text: Tango
      url: /tango/tango.html
    - text: Diplomas
      url: /diplomas/diplomas
    - text: Proyectos
      url: /content/proyectos
    # - text: Blog
    #   url: /blog

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: karlheitmann

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
